bds: BuildDataStructure.cpp formatutil.cpp TestUtil.cpp FDBG.cpp
	g++ -O3  -std=c++11 BuildDataStructure.cpp -o bds -l boost_log -l pthread
format: test_format.cpp
	g++ -O3  -std=c++11 test_format.cpp -o tf -l boost_log -l pthread -l bf
